### ISSUE TITLE
cursor.Parse() should treat EOF as empty member

### ISSUE THREAD

**Issue by pxue** [soundcloud/roshi#37]
when parsing a cursor string with empty member, ie:
`4743834931740803072A`
should be parse as a Cursor with empty Member field, currently Parse throws an `io.EOF` error.

I see there's a test case with `Member: " "` but that seems counter-intuitive

**Comment by beorn7** [comment]
@pxue Thanks for reporting.

@peterbourgon Can you still read this? Are you planning to maintain Roshi and deal with issues like this one? Which would raise the question about merge rights. The repo is public, but I guess only SC employees can merge PRs. I could proxy you for the time being so that we don't need to move the repo. What do you think?

**Comment by peterbourgon** [comment]
I'm happy to fix this issue via PR, but I can't commit to providing ongoing maintenance. I would also abstain from any vote about moving the repo to some other organization.

**Comment by beorn7** [comment]
Alright. Then @peterbourgon will fix this one, I'll merge his PR, and if anything comes up in the future, we'll take a raincheck. The repo stays where it is for as long as things work out.
